// GENERATED by scripts/embed-migrations.mjs from ./drizzle — do not edit.
export const MIGRATIONS: ReadonlyArray<{ tag: string; statements: readonly string[] }> = [
  {
    "tag": "0000_init",
    "statements": [
      "CREATE TABLE `change_log` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`timestamp` text NOT NULL,\n\t`actor` text NOT NULL,\n\t`command_type` text NOT NULL,\n\t`entity_type` text NOT NULL,\n\t`entity_id` text NOT NULL,\n\t`correlation_id` text NOT NULL,\n\t`summary` text NOT NULL,\n\t`state_revision` integer NOT NULL\n);",
      "CREATE INDEX `change_log_entity_idx` ON `change_log` (`entity_type`,`entity_id`);",
      "CREATE TABLE `meta` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`state_revision` integer NOT NULL,\n\tCONSTRAINT \"meta_single_row\" CHECK(\"meta\".\"id\" = 1)\n);",
      "CREATE TABLE `probes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`version` integer NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);"
    ]
  },
  {
    "tag": "0001_seed_meta",
    "statements": [
      "-- Custom SQL migration: the single global revision row (ARCHITECTURE §14).\nINSERT INTO `meta` (`id`, `state_revision`) VALUES (1, 0);"
    ]
  },
  {
    "tag": "0002_drop_probes",
    "statements": [
      "DROP TABLE `probes`;"
    ]
  },
  {
    "tag": "0003_add_intention_domain",
    "statements": [
      "CREATE TABLE `actions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`stage_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`done_when` text NOT NULL,\n\t`position` integer NOT NULL,\n\t`status` text NOT NULL,\n\t`blocker_reason` text,\n\t`blocked_at` text,\n\t`completed_at` text,\n\t`version` integer NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`stage_id`) REFERENCES `stages`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `actions_stage_idx` ON `actions` (`stage_id`);",
      "CREATE TABLE `good_life_conditions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`text` text NOT NULL,\n\t`position` integer NOT NULL,\n\t`version` integer NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);",
      "CREATE TABLE `intentions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`desired_result` text NOT NULL,\n\t`version` integer NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);",
      "CREATE TABLE `season` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`focus` text NOT NULL,\n\t`version` integer NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);",
      "CREATE TABLE `stages` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`intention_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`position` integer NOT NULL,\n\t`is_current` integer NOT NULL,\n\t`version` integer NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`intention_id`) REFERENCES `intentions`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `stages_intention_idx` ON `stages` (`intention_id`);"
    ]
  },
  {
    "tag": "0004_add_plans_and_proposals",
    "statements": [
      "CREATE TABLE `ordered_action_plans` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`intention_id` text NOT NULL,\n\t`ordered_action_ids` text NOT NULL,\n\t`rationale` text NOT NULL,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer NOT NULL,\n\t`source_revision` integer NOT NULL,\n\tFOREIGN KEY (`intention_id`) REFERENCES `intentions`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `ordered_action_plans_intention_idx` ON `ordered_action_plans` (`intention_id`);",
      "CREATE TABLE `proposals` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`kind` text NOT NULL,\n\t`status` text NOT NULL,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`base_revision` integer NOT NULL,\n\t`base_fingerprint` text NOT NULL,\n\t`affected_entity_ids` text NOT NULL,\n\t`payload` text NOT NULL,\n\t`rationale` text NOT NULL,\n\t`resolved_at` text,\n\t`resolved_by` text\n);",
      "CREATE INDEX `proposals_status_idx` ON `proposals` (`status`);"
    ]
  },
  {
    "tag": "0005_add_proposal_summary",
    "statements": [
      "ALTER TABLE `proposals` ADD `summary` text DEFAULT '' NOT NULL;"
    ]
  },
  {
    "tag": "0006_add_calendar_snapshot",
    "statements": [
      "CREATE TABLE `calendar_snapshot` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`connected` integer NOT NULL,\n\t`synced_at` text,\n\t`source` text,\n\t`time_zone` text,\n\t`events` text NOT NULL,\n\t`last_error` text,\n\tCONSTRAINT \"calendar_snapshot_single_row\" CHECK(\"calendar_snapshot\".\"id\" = 1)\n);"
    ]
  },
  {
    "tag": "0007_seed_calendar_snapshot",
    "statements": [
      "-- Custom SQL migration: the single calendar snapshot row (ARCHITECTURE §32), disconnected until the user authorizes Google Calendar.\nINSERT INTO `calendar_snapshot` (`id`, `connected`, `synced_at`, `source`, `time_zone`, `events`, `last_error`) VALUES (1, 0, NULL, NULL, NULL, '[]', NULL);"
    ]
  },
  {
    "tag": "0008_add_work_intervals",
    "statements": [
      "CREATE TABLE `settings` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`daily_work_target_minutes` integer NOT NULL,\n\tCONSTRAINT \"settings_single_row\" CHECK(\"settings\".\"id\" = 1)\n);",
      "CREATE TABLE `work_intervals` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`action_id` text NOT NULL,\n\t`started_at` text NOT NULL,\n\t`ended_at` text,\n\t`last_heartbeat_at` text NOT NULL,\n\t`time_zone` text NOT NULL,\n\tFOREIGN KEY (`action_id`) REFERENCES `actions`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `work_intervals_action_idx` ON `work_intervals` (`action_id`);",
      "CREATE INDEX `work_intervals_started_idx` ON `work_intervals` (`started_at`);",
      "CREATE UNIQUE INDEX `work_intervals_one_running_idx` ON `work_intervals` ((1)) WHERE \"work_intervals\".\"ended_at\" IS NULL;"
    ]
  },
  {
    "tag": "0009_seed_settings",
    "statements": [
      "-- Custom SQL migration: the single settings row; the daily work target starts at 6 hours (DEVELOPMENT_PLAN §4.4) and is user-changeable.\nINSERT INTO `settings` (`id`, `daily_work_target_minutes`) VALUES (1, 360);"
    ]
  },
  {
    "tag": "0010_add_captures_and_memories",
    "statements": [
      "CREATE TABLE `captures` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`raw_text` text NOT NULL,\n\t`source` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`state` text NOT NULL,\n\t`attempts` integer NOT NULL,\n\t`last_error` text,\n\t`result` text,\n\t`updated_at` text NOT NULL\n);",
      "CREATE INDEX `captures_state_idx` ON `captures` (`state`,`created_at`);",
      "CREATE INDEX `captures_created_idx` ON `captures` (`created_at`);",
      "CREATE TABLE `memories` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`type` text NOT NULL,\n\t`text` text NOT NULL,\n\t`source_capture_id` text,\n\t`linked_entity_ids` text NOT NULL,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`source_capture_id`) REFERENCES `captures`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `memories_source_capture_idx` ON `memories` (`source_capture_id`);"
    ]
  },
  {
    "tag": "0011_capture_raw_text_immutable",
    "statements": [
      "-- Custom SQL migration: the raw `+` original is immutable as a database fact (ARCHITECTURE §34, ADR-0007).\nCREATE TRIGGER `captures_raw_text_immutable` BEFORE UPDATE OF `raw_text` ON `captures`\nWHEN NEW.`raw_text` IS NOT OLD.`raw_text`\nBEGIN\n  SELECT RAISE(ABORT, 'captures.raw_text is immutable');\nEND;"
    ]
  },
  {
    "tag": "0012_capture_proposal_link",
    "statements": [
      "ALTER TABLE `captures` ADD `proposal_id` text;",
      "-- Custom backfill for Captures processed before the link existed (Stage 6, Gate B). A recorded result names\n-- its Proposal; a failed attempt is linked to the mcp-ai Proposal created between that attempt's claim and\n-- its finish (processing is single-flight, one desktop per database).\n-- ponytail: an mcp-ai Proposal from another MCP host inside that window would be misattributed; only\n-- pre-link history is affected, every newer run is linked explicitly through its context.\nUPDATE `captures` SET `proposal_id` = json_extract(`result`, '$.proposalId')\nWHERE `proposal_id` IS NULL AND json_extract(`result`, '$.proposalId') IS NOT NULL;",
      "UPDATE `captures` SET `proposal_id` = (\n  SELECT p.`entity_id` FROM `change_log` p\n  JOIN `change_log` c ON c.`entity_id` = `captures`.`id` AND c.`command_type` = 'capture.claim'\n  WHERE p.`command_type` = 'proposal.create' AND p.`actor` = 'mcp-ai' AND p.`timestamp` >= c.`timestamp`\n    AND p.`timestamp` < (\n      SELECT min(f.`timestamp`) FROM `change_log` f\n      WHERE f.`entity_id` = `captures`.`id` AND f.`command_type` IN ('capture.failed', 'capture.processed')\n        AND f.`timestamp` > c.`timestamp`\n    )\n  ORDER BY p.`timestamp` LIMIT 1\n)\nWHERE `proposal_id` IS NULL AND `state` = 'failed';"
    ]
  }
];
