// GENERATED by scripts/embed-migrations.mjs from ./drizzle — do not edit.
export const MIGRATIONS: ReadonlyArray<{ tag: string; statements: readonly string[] }> = [
  {
    "tag": "0000_init",
    "statements": [
      "CREATE TABLE `change_log` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`timestamp` text NOT NULL,\n\t`actor` text NOT NULL,\n\t`command_type` text NOT NULL,\n\t`entity_type` text NOT NULL,\n\t`entity_id` text NOT NULL,\n\t`correlation_id` text NOT NULL,\n\t`summary` text NOT NULL,\n\t`state_revision` integer NOT NULL\n);",
      "CREATE INDEX `change_log_entity_idx` ON `change_log` (`entity_type`,`entity_id`);",
      "CREATE TABLE `meta` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`state_revision` integer NOT NULL,\n\tCONSTRAINT \"meta_single_row\" CHECK(\"meta\".\"id\" = 1)\n);",
      "CREATE TABLE `probes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`version` integer NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);"
    ]
  },
  {
    "tag": "0001_seed_meta",
    "statements": [
      "-- Custom SQL migration: the single global revision row (ARCHITECTURE §14).\nINSERT INTO `meta` (`id`, `state_revision`) VALUES (1, 0);"
    ]
  }
];
